config/urls.py
from django.contrib import admin
from django.urls import path, include
from video.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('video/', include('video.urls')),
]

video/urls.py
from django.urls import path
from .views import *

app_name = 'video'

urlpatterns = [
    path('clean/', http1, name='clean'),
    path('rec/', http2, name='rec'),
    path('diff/', http3, name='diff'),
    path('text/', http_text, name='text')

]

video/models.py
from django.db import models

# Create your models here.

video/views.py
from django.shortcuts import render
from django.http.response import StreamingHttpResponse, HttpResponse

from .clean_Video import *
from .rec_recognition import *
from .diff_recognigion import *

from PIL import ImageDraw, Image
import io
import time


# Create your views here.


def index(request):
    return render(request, 'video/video.html')


def gen_clean():
    print('gen_clean 실행')
    dbj_clr = Clean_Video()
    while True:
        frame = dbj_clr.stream()

        frame = (b'--frame\r\n'
                 b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
        yield frame


obj_rr = Rectangle_Recognition()


def gen_rec():
    print('gen_rec 실행')
    time.sleep(3)
    # obj_rr = Rectangle_Recognition()
    while True:
        frame, text = obj_rr.stream()
        frame = (b'--frame\r\n'
                 b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
        yield frame


def gen_diff():
    print('gen_diff 실행')
    obj_dr = Diff_Recognition()
    while True:
        frame, _ = obj_dr.stream()

        frame = (
                b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

        yield frame


def gen_text():
    print('gen_text 실행')
    # obj_rr = Rectangle_Recognition()
    while True:
        img = Image.new('RGB', (200, 30), color=(255, 255, 255))
        d = ImageDraw.Draw(img)

        d.text((10, 15), obj_rr.text, fill=(0, 0, 0))
        byte = io.BytesIO()
        img.save(byte, format='JPEG')
        text = (b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + byte.getvalue() + b'\r\n\r\n')
        yield text
        img.close()


'''
def gen_text():
    print('gen_rec 실행')
    obj_rr = Rectangle_Recognition()
    while True:
        frame, text = obj_rr.stream()

        # text = (b'--frame\r\n'
        #         b'Content-Type: text/html\r\n\r\n' + text.encode() + b'\r\n\r\n')

        text2 = (b'<p>' + text.encode() + b'</p>')

        yield text2
'''


def http1(request):
    return StreamingHttpResponse(gen_clean(), content_type='multipart/x-mixed-replace; boundary=frame')


def http2(request):
    return StreamingHttpResponse(gen_rec(), content_type='multipart/x-mixed-replace; boundary=frame')


def http3(request):
    return StreamingHttpResponse(gen_diff(), content_type='multipart/x-mixed-replace; boundary=frame')


con1 = 'multipart/x-mixed-replace; boundary=frame'
con2 = 'text/html'


def http_text(request):
    return StreamingHttpResponse(gen_text(), content_type='multipart/x-mixed-replace; boundary=frame')

templates/base.html
{% load static %}

<html lang="ko">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>자산관리 웹 {% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">ARSLOOPER </div>
            </a>



            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                자산관리
            </div>

            <!-- Nav Item - Pages 자산 정보 -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>카메라</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="#">카메라</a>

                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                ~~~~
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                    aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>~~~</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="#">~~~</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown no-arrow">

                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'img/undraw_profile.svg'%}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="/admin">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="/admin/admin/logentry/">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item"><a href="#" class="nav-link">Login</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Signup</a></li>
                        {% endif %}
                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">


                {% block content %}
                {% endblock %}


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; ARSLOOPER</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>


    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>



</body>

</html>

templates/base_2.html
{% load static %}

<!-- <!DOCTYPE html> -->
<html lang="ko">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,700,900" rel="stylesheet">

    <title>자산관리 웹 {% block title %}{% endblock %} </title>
<!--
SOFTY PINKO
https://templatemo.com/tm-535-softy-pinko
-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}"> <!-- assets/css/bootstrap.min.css -->

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}"> <!-- assets/css/font-awesome.css -->

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/templatemo-softy-pinko.css' %}"> <!-- assets/css/templatemo-softy-pinko.css -->

         <!-- jQuery -->
    <script src="{% static 'assets/js/jquery-2.1.0.min.js' %}"></script> <!-- assets/js/jquery-2.1.0.min.js -->

    <!-- Bootstrap -->
    <script src="{% static 'assets/js/popper.js' %}"></script> <!-- assets/js/popper.js -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script> <!-- assets/js/bootstrap.min.js -->

    <!-- Plugins -->
    <script src="{% static 'assets/js/scrollreveal.min.js' %}"></script> <!-- assets/js/scrollreveal.min.js -->
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script> <!-- assets/js/waypoints.min.js -->
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script> <!-- assets/js/jquery.counterup.min.js -->
    <script src="{% static 'assets/js/imgfix.min.js' %}"></script>  <!-- assets/js/imgfix.min.js -->

    <!-- Global Init -->
    <script src="{% static 'assets/js/custom.js' %}"></script> <!-- assets/js/custom.js -->


    </head>
    
    <body>
    
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky" >
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="/" class="logo">
                            <img src="{% static 'assets/images/logo.png' %}" width="135px" height="30px"/>
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="/" class="nav-item active">Home</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-item dropdown-toggle" href="#" data-toggle="dropdown"> 자산관리 </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'item:item_upload' %}">자산등록</a>
                                    <a class="dropdown-item" href="{% url 'item:item_list' %}">자산현황</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-item dropdown-toggle" href="#" data-toggle="dropdown"> 사업관리 </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">사업등록</a>
                                    <a class="dropdown-item" href="{% url 'entry:entry_list' %}">사업현황</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-item dropdown-toggle" href="#" data-toggle="dropdown"> 사원관리 </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">사원등록</a>
                                    <a class="dropdown-item" href="#">사원수정</a>
                                    <a class="dropdown-item" href="#">사원삭제</a>
                                </div>
                            </li>
                            <li><a href="#pricing-plans">로그인</a></li>
                            <li><a href="#blog">로그아웃</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->


    {% block content %}
    {% endblock %}




    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="copyright">Copyright &copy; ARSLOOPER</p>
                </div>
            </div>
        </div>
    </footer>
    


  </body>
</html>

video/templates/video/qrcode_result.html
{% extends 'base.html' %}

{% load static %}
{% block title %}- {% endblock %}

{% block content %}

<p> {{object}}</p>

{% endblock %}

video/templates/video/text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

video/templates/video/video.html
{% extends 'base.html' %}

{% load static %}
{% block title %}- {% endblock %}

{% block content %}

<form action="#" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="image" name="img" src="{% url 'video:rec' %}">
	<input type="image" name="img" src="{% url 'video:text' %}">


</form>

{% endblock %}



<!--
	<input type="image" name="img" src="{% url 'video:rec' %}">
	<input type="image" name="img" src="{% url 'video:diff' %}">
	<input type="image" name="img" src="{% url 'video:clean' %}">
	<input type="image" name="img" src="{% url 'video:text' %}">
-->

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
	var x = new XMLHttpRequest();
	x.open("GET","https://consolekakao.github.io/");
	x.send();

	function test(){


	}
        });
</script>